### ISSUE TITLE
Improve header design

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/portotestersmeetup.github.io#15]
Header is different in style from the rest of the page

![screen shot 2017-10-10 at 17 26 15](https://user-images.githubusercontent.com/11976836/31398383-ac90ca3a-ade0-11e7-81b0-d7c0f4fa2098.png)

**Comment by filipemcarvalho** [comment]
@filfreire would you like to tackle this?

**Comment by filfreire** [comment]
@filipemcarvalho yes

**Comment by filfreire** [comment]
@filipemcarvalho can you assign me this issue?

**Comment by FabioCB** [comment]
@filfreire done

**Comment by filfreire** [comment]
@filipemcarvalho @FabioCB 
What do you think about this "design":
<img width="1588" alt="screen shot 2017-11-21 at 22 40 11" src="https://user-images.githubusercontent.com/11976836/33100652-0d34edba-cf0d-11e7-854b-fb4742d66fde.png">

It's simple and clean, and we avoid lot's of different colours.

Can I open a PR with the necessary changes?

**Comment by filipemcarvalho** [comment]
Personally I like it. Clean and simple 👍

**Comment by tjbfernandes** [comment]
# 1. mobile menu close
![image](https://user-images.githubusercontent.com/12085695/33125451-6e03b142-cf78-11e7-968c-e34751fb5545.png)

# 2. mobile menu open
![image](https://user-images.githubusercontent.com/12085695/33125439-58a5a92c-cf78-11e7-9d20-962224385beb.png)

# 3. desktop 
![image](https://user-images.githubusercontent.com/12085695/33125464-78a10672-cf78-11e7-92f0-c0b308a1bb58.png)

**Comment by filfreire** [comment]
Closing this issue since the PR #40 was merged.
