### ISSUE TITLE
Add favicon to PTM page

### ISSUE THREAD

**Issue by filipemcarvalho** [PortoTestersMeetup/portotestersmeetup.github.io#17]
[Reference](https://en.wikipedia.org/wiki/Favicon)
The file is in images/icon/*.icon .

**Comment by filfreire** [comment]
@filipemcarvalho we should also add the `help wanted` and  `hacktoberfest` label 👍

**Comment by filipemcarvalho** [comment]
Good idea, just did it 👍

**Comment by omergulen** [comment]
Done!
