### ISSUE TITLE
Add a way to easily go back to "home" page from the "calling for venues" and the "calling for speakers" page

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/portotestersmeetup.github.io#23]
Add a way to easily go back to "home" page from the "calling from venues" and the "calling for speakers" pages.
It could be by 2 ways combined: 
- Clicking on the Porto Testers Meetup title;
- Back button on the end of the page, outside of the google form frame.

@FabioCB @filipemcarvalho FYI

**Comment by filfreire** [comment]
@FabioCB @filipemcarvalho this is also a good issue to add labels like 
the ones on issue https://github.com/PortoTestersMeetup/portotestersmeetup.github.io/issues/17

**Comment by filipemcarvalho** [comment]
What do you guys think of doing the same to the 'Call for speakers page' too? @filfreire @FabioCB 
Agree. I will add the labels 👍

**Comment by filfreire** [comment]
@filipemcarvalho agreed.
We should create another issue or change this one then.
(edit: to encompass both pages)

**Comment by filipemcarvalho** [comment]
I would suggest changing this one as the solution applied should be coherent and then the same to both pages 👍

**Comment by filfreire** [comment]
@filipemcarvalho updated title and description

**Comment by jgrrdnd** [comment]
I'd like to give this a try.

**Comment by FabioCB** [comment]
@jgrrdnd go for it

**Comment by jgrrdnd** [comment]
actually im not familiar with editing Github Pages. I will have to resign, sorry

**Comment by AugustasV** [comment]
I want to do that!

**Comment by filipemcarvalho** [comment]
You can go for it @AugustasV 👍

**Comment by filfreire** [comment]
@AugustasV did it in PR #26 
@FabioCB @filipemcarvalho please follow-up with a CR 👍

**Comment by filipemcarvalho** [comment]
Resolved by @AugustasV in #26 .
