### ISSUE TITLE
Add Filipe Freire's info

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/portotestersmeetup.github.io#30]
**Purpose:**
Add Filipe Freire's info and picture to porto testers meetup page.

**Comment by filfreire** [comment]
@FabioCB @filipemcarvalho please assign this issue to me.

**Comment by filfreire** [comment]
@filipemcarvalho @FabioCB PR #34 closes this issue

**Comment by filipemcarvalho** [comment]
Closed as it has been tackled in #34 👍
