### ISSUE TITLE
Redesign home button in CFS and CFV pages

### ISSUE THREAD

**Issue by filipemcarvalho** [PortoTestersMeetup/portotestersmeetup.github.io#31]
The idea is to make the button prettier and more user friendly 👍 

Food for thought: This can be made as a generic component to be reused in other buttons of the website.

Reference pages: 
https://portotestersmeetup.github.io/pages/cfs
https://portotestersmeetup.github.io/pages/cfv

**Comment by filfreire** [comment]
@FabioCB @filipemcarvalho PR is merged, kindly close this issue.
