### ISSUE TITLE
Add a Past Events page

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/portotestersmeetup.github.io#33]
Let's add a past events page with a list of past events, and links to both slides, videos (if we have them) and also speakers contacts.

**Comment by filfreire** [comment]
@filipemcarvalho @FabioCB FYI

**Comment by filipemcarvalho** [comment]
Totally agree. This was in the backlog and I've started some work related to this some time ago. For the mean time, I will assign this for me and tackle it as soon as possible 👍
