### ISSUE TITLE
Setup integration with PTM's Slack channel

### ISSUE THREAD

**Issue by filfreire** [PortoTestersMeetup/portotestersmeetup.github.io#39]
**Tasks:**
- Integrate created PRs & created issues with PTM's `#website-contrib` channel.

**Comment by filfreire** [comment]
@FabioCB @filipemcarvalho FYI

**Comment by filipemcarvalho** [comment]
Closing as this has been done in the #website-contrib channel 👍

**Comment by filfreire** [comment]
@filipemcarvalho nice 👍
